// AUTO-GENERATED by design/icon-options/build-registry.py.
// Source of truth = design/icon-options/batch*/manifest.json.
// To add a batch: run the `generate-app-icons` workflow, write its
// design/icon-options/batch<N>/manifest.json (batch,num,label,date,themes,icons),
// then rerun build-registry.py. Do not hand-edit this file.

export type IconConcept = { id: string; file: string; name: string; concept: string; score: number | null };
export type ThemeGroup = { title: string; icons: IconConcept[] };
export type Batch = { batch: string; num: number; label: string; date: string; themes: ThemeGroup[] };

export const BATCHES: Batch[] = [
  {
    "batch": "batch1",
    "num": 1,
    "label": "Foundations",
    "date": "2026-05-31",
    "themes": [
      {
        "title": "The E / Rising-Rating Chart",
        "icons": [
          {
            "id": "B1-01",
            "file": "team1-e-a",
            "name": "Ascending bars + gold peak",
            "concept": "Heavy red E from ascending bars with a gold breakthrough peak, on Void.",
            "score": null
          },
          {
            "id": "B1-02",
            "file": "team1-e-b",
            "name": "Negative-space red tile",
            "concept": "An E knocked out of a solid Signal Red tile in negative space.",
            "score": null
          },
          {
            "id": "B1-03",
            "file": "team1-e-c",
            "name": "Abstract step-climb",
            "concept": "An abstract step-chart staircase that implies the E's ascending bars.",
            "score": null
          }
        ]
      },
      {
        "title": "Typographic Monogram",
        "icons": [
          {
            "id": "B1-04",
            "file": "team2-mono-a",
            "name": "ER stamped monogram",
            "concept": "Stamped white ER monogram on a full-bleed Signal Red tile.",
            "score": null
          },
          {
            "id": "B1-05",
            "file": "team2-mono-b",
            "name": "ELO (O = rating dial)",
            "concept": "ELO wordmark with the O rendered as a red rating dial / medallion.",
            "score": null
          },
          {
            "id": "B1-06",
            "file": "team2-mono-c",
            "name": "Monolithic E slab",
            "concept": "Monolithic white E on deep brand red with a thin gold baseline.",
            "score": null
          }
        ]
      },
      {
        "title": "The BJJ Belt",
        "icons": [
          {
            "id": "B1-07",
            "file": "team3-belt-a",
            "name": "BJJ belt knot",
            "concept": "Head-on tied gi belt knot with white rank stripes and a gold next-rank stripe.",
            "score": null
          },
          {
            "id": "B1-08",
            "file": "team3-belt-b",
            "name": "Belt = rating bar",
            "concept": "A belt band whose rank-bar stripes double as an ELO progress meter.",
            "score": null
          },
          {
            "id": "B1-09",
            "file": "team3-belt-c",
            "name": "Diagonal belt sash",
            "concept": "An abstract white belt sash crossing a deep-red tile.",
            "score": null
          }
        ]
      },
      {
        "title": "Grappling / The Lock",
        "icons": [
          {
            "id": "B1-10",
            "file": "team4-grapple-a",
            "name": "Interlocked triangles",
            "concept": "Two interlocking triangles: the triangle choke / closed guard.",
            "score": null
          },
          {
            "id": "B1-11",
            "file": "team4-grapple-b",
            "name": "Clinched / matched",
            "concept": "Two clinched angular hooks reading as two matched competitors.",
            "score": null
          },
          {
            "id": "B1-12",
            "file": "team4-grapple-c",
            "name": "Fist on gi lapel",
            "concept": "A bold white fist gripping a diagonal Signal Red gi lapel.",
            "score": null
          }
        ]
      },
      {
        "title": "Rating / The Climb",
        "icons": [
          {
            "id": "B1-13",
            "file": "team5-rating-a",
            "name": "Up-delta + bar chart",
            "concept": "A Gain-Green upward delta rising out of an ascending bar chart.",
            "score": null
          },
          {
            "id": "B1-14",
            "file": "team5-rating-b",
            "name": "Podium + chevron",
            "concept": "Bronze/silver/gold podium crowned by a Signal-Red up-chevron.",
            "score": null
          },
          {
            "id": "B1-15",
            "file": "team5-rating-c",
            "name": "Medallion up-arrow",
            "concept": "A Signal-Red rank medallion with an up-arrow in negative space.",
            "score": null
          }
        ]
      },
      {
        "title": "The Statement (Brutalist)",
        "icons": [
          {
            "id": "B1-16",
            "file": "team6-statement-a",
            "name": "Diagonal slash",
            "concept": "A bold diagonal Signal-Red slash with a thin gold seam.",
            "score": null
          },
          {
            "id": "B1-17",
            "file": "team6-statement-b",
            "name": "Monolith / flag",
            "concept": "A planted red monolith / flag with a swallowtail notch and gold cap.",
            "score": null
          },
          {
            "id": "B1-18",
            "file": "team6-statement-c",
            "name": "Impact emblem",
            "concept": "A nested-square impact emblem with a Signal-Red diamond core.",
            "score": null
          }
        ]
      }
    ]
  },
  {
    "batch": "batch3",
    "num": 3,
    "label": "Round 3",
    "date": "2026-06-01",
    "themes": [
      {
        "title": "Lettermark E / ER Monogram",
        "icons": [
          {
            "id": "B3-01",
            "file": "theme1-lettermark-a",
            "name": "Ascending E",
            "concept": "Heavy slab letter E whose three rungs grow in length into a rising ELO chart, capped by a gold breakthrough peak on deep brand red.",
            "score": 4
          },
          {
            "id": "B3-02",
            "file": "theme1-lettermark-b",
            "name": "ER Monogram Tile",
            "concept": "Bold locked E+R monogram in white on a Signal Red rounded tile over Void, the heavy brand signature.",
            "score": 5
          },
          {
            "id": "B3-03",
            "file": "theme1-lettermark-c",
            "name": "Floating-Bar E",
            "concept": "Abstract spineless E built from three free-floating ascending bars reading as a bar chart, with a tall gold breakthrough column.",
            "score": 4
          }
        ]
      },
      {
        "title": "The Belt & Rank",
        "icons": [
          {
            "id": "B3-04",
            "file": "theme2-belt-a",
            "name": "Tied Knot",
            "concept": "Head-on tied gi belt knot with a white-and-red cinch, hanging tails with a red rank tip, and a striped red rank bar.",
            "score": 3
          },
          {
            "id": "B3-05",
            "file": "theme2-belt-b",
            "name": "Rank Meter",
            "concept": "Belt band whose rank stripes become a climbing segmented ELO meter rising to a gold breakthrough segment.",
            "score": 3
          },
          {
            "id": "B3-06",
            "file": "theme2-belt-c",
            "name": "Diagonal Belt",
            "concept": "Abstract brutalist black belt sweeping diagonally across a red field, with a striped rank tab and red leading tip.",
            "score": 4
          }
        ]
      },
      {
        "title": "The Mat & Guard",
        "icons": [
          {
            "id": "B3-07",
            "file": "theme3-mat-a",
            "name": "Tatami Arena",
            "concept": "Top-down competition mat: Signal Red safety apron, gridded dark combat area, white center circle with a red live-match node.",
            "score": 5
          },
          {
            "id": "B3-08",
            "file": "theme3-mat-b",
            "name": "Closed Guard",
            "concept": "Abstract closed-guard position diagram: a red wrapping frame with the crossed-ankle X lock at top, clamping the trapped white torso.",
            "score": 3
          },
          {
            "id": "B3-09",
            "file": "theme3-mat-c",
            "name": "The Match",
            "concept": "Matchmaking mark of two zones (red vs white) interlocking along a dovetail void seam, each holding one engagement node.",
            "score": 4
          }
        ]
      },
      {
        "title": "Rating & Ascension",
        "icons": [
          {
            "id": "B3-10",
            "file": "theme4-ascend-a",
            "name": "Delta Climb",
            "concept": "Heavy stacked upward chevron-delta launching out of an ascending bar chart, gold breakthrough cap at the apex.",
            "score": 5
          },
          {
            "id": "B3-11",
            "file": "theme4-ascend-b",
            "name": "Podium Tiers",
            "concept": "Three ascending podium steps low-to-high with a gold-crowned Signal Red top tier carrying a knocked-out up-arrow.",
            "score": 3
          },
          {
            "id": "B3-12",
            "file": "theme4-ascend-c",
            "name": "Rank Medallion",
            "concept": "Bold hexagonal rank medallion holding an up-arrow over an ascending step-base, gold crown notch at the peak.",
            "score": 4
          }
        ]
      },
      {
        "title": "The Lock (Combat)",
        "icons": [
          {
            "id": "B3-13",
            "file": "theme5-combat-a",
            "name": "Triangle Lock",
            "concept": "Two heavy interlocking triangle frames woven over/under (Signal Red up, Terminal White down) with a central choke node, reading as a triangle choke / closed guard.",
            "score": 5
          },
          {
            "id": "B3-14",
            "file": "theme5-combat-b",
            "name": "Gi Grip",
            "concept": "A solid white fist with blocky knuckles and a wrapping thumb clamping a bold diagonal Signal Red gi lapel corner to corner.",
            "score": 4
          },
          {
            "id": "B3-15",
            "file": "theme5-combat-c",
            "name": "Matched Clinch",
            "concept": "Two mirror-symmetric figures (white vs red) clinched at interlocking arms across a central Void seam, a balanced, evenly-weighted heraldic pair.",
            "score": 3
          }
        ]
      },
      {
        "title": "Brutalist Statement",
        "icons": [
          {
            "id": "B3-16",
            "file": "theme6-statement-a",
            "name": "The Cut",
            "concept": "A bold diagonal slash splits the tile Void-over-Signal-Red, with a white E (plus gold breakthrough step) above the cut and a mirrored knocked-out E below it.",
            "score": 4
          },
          {
            "id": "B3-17",
            "file": "theme6-statement-b",
            "name": "Planted Flag",
            "concept": "A heavy white monolith planted dead-center with a gold breakthrough cap, a massive Signal Red flag blade flying off it, and a red base wedge driving it into the ground.",
            "score": 3
          },
          {
            "id": "B3-18",
            "file": "theme6-statement-c",
            "name": "Impact Diamond",
            "concept": "Nested rotated Void/Red squares collapsing to a core, with two opposing force halves (Terminal White vs Gold) colliding at a hard Void seam and central impact block.",
            "score": 5
          }
        ]
      }
    ]
  },
  {
    "batch": "batch2",
    "num": 2,
    "label": "Themed Territories",
    "date": "2026-06-01",
    "themes": [
      {
        "title": "Lettermark E / ER Monogram",
        "icons": [
          {
            "id": "B2-01",
            "file": "theme1-lettermark-a",
            "name": "Ascending-Bar E",
            "concept": "Red-spine letter E with white arms of ascending length (E + rising ELO chart) and a gold breakthrough peak stepping above the top bar, on Void.",
            "score": 3
          },
          {
            "id": "B2-02",
            "file": "theme1-lettermark-b",
            "name": "ER Monogram Tile",
            "concept": "Heavy white ER monogram (bold condensed E plus an R with proper bowl, counter, and diagonal leg) seated on a Void plate inside a full-bleed Signal Red tile.",
            "score": 5
          },
          {
            "id": "B2-03",
            "file": "theme1-lettermark-c",
            "name": "Staircase E Lettermark",
            "concept": "Abstract modern E rendered as a solid Signal Red stem with three cantilevered arms of ascending length, white tip-caps marking each arm, and a gold breakthrough cap rising above the longest arm.",
            "score": 4
          }
        ]
      },
      {
        "title": "The Belt & Rank",
        "icons": [
          {
            "id": "B2-04",
            "file": "theme2-belt-a",
            "name": "Tied Knot",
            "concept": "Head-on tied gi belt knot crossing a dark belt band, with a four-stripe rank bar and a red rank-tipped hanging tail.",
            "score": 4
          },
          {
            "id": "B2-05",
            "file": "theme2-belt-b",
            "name": "Rank Meter Belt",
            "concept": "Horizontal belt band whose black rank-tab stripes fill left-to-right as a red-to-gold ELO progress meter, climbing to a gold breakthrough stripe.",
            "score": 3
          },
          {
            "id": "B2-06",
            "file": "theme2-belt-c",
            "name": "Diagonal Rank Mark",
            "concept": "Abstract modern belt: a heavy black band sweeps diagonally across a deep-red ground with an inset rank tab of three white stripes and one red, edged in Signal Red.",
            "score": 4
          }
        ]
      },
      {
        "title": "The Mat & Guard",
        "icons": [
          {
            "id": "B2-07",
            "file": "theme3-mat-a",
            "name": "Tatami Arena",
            "concept": "Top-down brutalist competition mat: tatami tile grid framing a central Signal Red contest zone with a referee cross and engagement dot.",
            "score": 4
          },
          {
            "id": "B2-08",
            "file": "theme3-mat-b",
            "name": "Closed Guard",
            "concept": "Abstract closed-guard position glyph: red legs wrap and lock with a crossed-ankle X over a controlled white torso gripped by two bars.",
            "score": 3
          },
          {
            "id": "B2-09",
            "file": "theme3-mat-c",
            "name": "Two Zones",
            "concept": "Matchmaking mark: the arena circle split into red and white zones interlocking on a bold dovetail seam, one athlete dot per side.",
            "score": 5
          }
        ]
      },
      {
        "title": "Rating & Ascension",
        "icons": [
          {
            "id": "B2-10",
            "file": "theme4-ascend-a",
            "name": "Breakthrough Trend",
            "concept": "Ascending bar chart with a heavy Signal Red trend arrow surging over a gold breakthrough bar to an up-arrowhead peak.",
            "score": 5
          },
          {
            "id": "B2-11",
            "file": "theme4-ascend-b",
            "name": "Podium Climb",
            "concept": "Ascending staircase podium on brand red with a highlighted white top tier carved with an upward arrow.",
            "score": 3
          },
          {
            "id": "B2-12",
            "file": "theme4-ascend-c",
            "name": "ELO Ascent Lettermark",
            "concept": "Bold geometric ELO lettermark whose letters rise in height, the tallest O a red ring capped with a gold peak.",
            "score": 3
          }
        ]
      },
      {
        "title": "The Lock (Combat)",
        "icons": [
          {
            "id": "B2-13",
            "file": "theme5-combat-a",
            "name": "Triangle Lock",
            "concept": "Two interlocking triangles (triangle choke / closed guard) woven over-under with a locked red center node.",
            "score": 3
          },
          {
            "id": "B2-14",
            "file": "theme5-combat-b",
            "name": "Lapel Grip",
            "concept": "A heavy white fist with four knuckles and a wrapping thumb clamping a bold diagonal Signal Red gi lapel.",
            "score": 4
          },
          {
            "id": "B2-15",
            "file": "theme5-combat-c",
            "name": "Matched Clinch",
            "concept": "Two mirror-symmetric figures (white vs void) clinched and bound by a red seam into one balanced, evenly-weighted mark.",
            "score": 3
          }
        ]
      },
      {
        "title": "Brutalist Statement",
        "icons": [
          {
            "id": "B2-16",
            "file": "theme6-statement-a",
            "name": "The Cut",
            "concept": "A bold diagonal slash divides the tile into void and Signal Red, with a brutalist E (gold breakthrough peak) carved in the dark half and a mirrored void glyph in the red half.",
            "score": 4
          },
          {
            "id": "B2-17",
            "file": "theme6-statement-b",
            "name": "Planted Monolith",
            "concept": "A single heavy black slab driven into a deep-red ground, capped in gold with a Signal Red flag blade flying off it and a white impact band at the strike point.",
            "score": 3
          },
          {
            "id": "B2-18",
            "file": "theme6-statement-c",
            "name": "Impact Nest",
            "concept": "Concentric squares collapsing toward a white core with gold and Signal Red collision wedges driving in from opposing corners: two athletes meeting at the center.",
            "score": 4
          }
        ]
      }
    ]
  }
];
