import {
  BATCHES,
  type Batch,
  type IconConcept,
} from "./icons.data";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

function formatDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  if (!y || !m || !d) return iso;
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

function IconTile({ batch, icon }: { batch: string; icon: IconConcept }) {
  return (
    <figure className="w-24 space-y-1.5">
      {/* iOS-style rounded mask previews how the icon reads on a device. */}
      <div className="overflow-hidden rounded-[22%] ring-1 ring-border">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`/design/icons/${batch}/${icon.file}.svg`}
          alt={`Icon ${icon.id}: ${icon.name}. ${icon.concept}`}
          title={`${icon.id}: ${icon.name}. ${icon.concept}`}
          width={96}
          height={96}
          className="block aspect-square w-full"
        />
      </div>
      <figcaption className="space-y-0.5">
        <div className="flex items-center gap-1">
          <span className="rounded-sm bg-secondary px-1 py-px font-mono text-[10px] font-bold tabular-nums text-foreground">
            {icon.id}
          </span>
          {typeof icon.score === "number" && (
            <span className="font-mono text-[10px] tabular-nums text-muted-foreground">
              {icon.score}/5
            </span>
          )}
        </div>
        <p className="font-body text-[11px] leading-tight text-muted-foreground">
          {icon.name}
        </p>
      </figcaption>
    </figure>
  );
}

function ThemeBlock({ batch, title, icons }: { batch: string; title: string; icons: IconConcept[] }) {
  return (
    <div className="space-y-3">
      <h3 className="font-heading text-xs uppercase tracking-widest text-muted-foreground">
        {title}
      </h3>
      <div className="flex flex-wrap gap-x-5 gap-y-4">
        {icons.map((icon) => (
          <IconTile key={icon.id} batch={batch} icon={icon} />
        ))}
      </div>
    </div>
  );
}

function BatchSection({ batch }: { batch: Batch }) {
  const count = batch.themes.reduce((n, t) => n + t.icons.length, 0);
  return (
    <section className="space-y-6 border-t-2 border-border pt-8">
      <div className="space-y-1.5">
        <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
          <span className="font-mono text-sm font-bold tabular-nums text-primary">
            B{batch.num}
          </span>
          <h2 className="font-display text-3xl uppercase leading-none text-foreground">
            {batch.label}
          </h2>
        </div>
        <p className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
          {formatDate(batch.date)} · {count} icons · IDs B{batch.num}-01–B
          {batch.num}-{String(count).padStart(2, "0")}
        </p>
      </div>

      <div className="grid grid-cols-1 gap-x-10 gap-y-8 lg:grid-cols-2 2xl:grid-cols-3">
        {batch.themes.map((theme) => (
          <ThemeBlock
            key={theme.title}
            batch={batch.batch}
            title={theme.title}
            icons={theme.icons}
          />
        ))}
      </div>
    </section>
  );
}

export default function AppIconConceptsPage() {
  const totalIcons = BATCHES.reduce(
    (n, b) => n + b.themes.reduce((m, t) => m + t.icons.length, 0),
    0,
  );

  return (
    <div className="space-y-14">
      <section className="max-w-2xl space-y-3 pt-4">
        <h1 className="font-display text-5xl uppercase leading-none text-foreground">
          App Icon Concepts
        </h1>
        <p className="font-body text-muted-foreground">
          Candidate ELO RATED app icons, generated by theme ({BATCHES.length}{" "}
          batches, {totalIcons} icons). Each row is one theme with its three
          variants. The Foundations batch is pinned at the top as the reference
          set; newer{" "}
          <span className="font-mono text-sm text-foreground">
            generate-app-icons
          </span>{" "}
          runs follow, newest first. Every icon has a stable ID like{" "}
          <span className="font-mono text-sm text-foreground">B2-07</span>;
          quote it when comparing notes, and hover any icon for its full concept.
        </p>
      </section>

      {BATCHES.map((batch) => (
        <BatchSection key={batch.batch} batch={batch} />
      ))}
    </div>
  );
}
