#!/usr/bin/env python3
"""Build the App Icon Concepts registry for the web design section.

Scans every `design/icon-options/batch*/manifest.json`, copies each batch's SVGs
into `apps/web/public/design/icons/<batch>/`, assigns a stable stakeholder ID to
every icon (e.g. `B2-07`), and regenerates the page data module
`apps/web/app/design/app-icon-concepts/icons.data.ts`.

Idempotent and ADDITIVE: rerunning after a new `generate-app-icons` workflow run
(which drops a new `batch<N>/` with a `manifest.json`) simply appends that batch
as a new dated section. Nothing is removed.

Each `manifest.json` must contain: batch, num, label, date (ISO YYYY-MM-DD),
themes: [{key,title}], icons: [{theme, themeTitle, file, name, concept, score}].

Usage:  python3 design/icon-options/build-registry.py
"""
import json
import glob
import os
import re
import shutil

# Em-dash (U+2014) and horizontal bar (U+2015) are banned in prose (global style
# rule). Workflow agents sometimes emit them in concept text, so normalize any
# (with surrounding whitespace) to a comma. Defense-in-depth on top of clean sources.
_DASH_RE = re.compile(r"\s*[—―]\s*")


def sanitize(s: str) -> str:
    return _DASH_RE.sub(", ", s)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ICON_DIR = os.path.join(ROOT, "design", "icon-options")
PUBLIC = os.path.join(ROOT, "apps", "web", "public", "design", "icons")
DATA_TS = os.path.join(
    ROOT, "apps", "web", "app", "design", "app-icon-concepts", "icons.data.ts"
)


def load_batches():
    batches = []
    for mf in glob.glob(os.path.join(ICON_DIR, "batch*", "manifest.json")):
        with open(mf) as f:
            batches.append(json.load(f))
    batches.sort(key=lambda b: b["num"])
    return batches


def copy_assets(b):
    src = os.path.join(ICON_DIR, b["batch"], "svg")
    dst = os.path.join(PUBLIC, b["batch"])
    os.makedirs(dst, exist_ok=True)
    for ic in b["icons"]:
        s = os.path.join(src, ic["file"] + ".svg")
        if not os.path.exists(s):
            raise SystemExit(f"MISSING asset: {s} (referenced by {b['batch']})")
        shutil.copy2(s, os.path.join(dst, ic["file"] + ".svg"))


def to_theme_groups(b):
    """Group icons by theme (in manifest theme order), then assign IDs B<num>-NN
    in display order so the IDs are always contiguous within a group regardless of
    how the manifest's `icons` array happens to be ordered."""
    title_by_key = {t["key"]: t["title"] for t in b["themes"]}
    order = [t["key"] for t in b["themes"]]
    unknown = sorted({ic["theme"] for ic in b["icons"]} - set(order))
    if unknown:
        raise SystemExit(
            f"{b['batch']}: icons reference themes missing from manifest.themes: {unknown}"
        )

    grouped = {k: [] for k in order}
    for ic in b["icons"]:
        grouped[ic["theme"]].append(ic)

    result = []
    counter = 0
    for k in order:
        if not grouped[k]:
            continue
        icons = []
        for ic in grouped[k]:
            counter += 1
            icons.append(
                {
                    "id": f"B{b['num']}-{counter:02d}",
                    "file": ic["file"],
                    "name": sanitize(ic["name"]),
                    "concept": sanitize(ic["concept"]),
                    "score": ic.get("score"),
                }
            )
        result.append({"title": title_by_key.get(k, k), "icons": icons})
    return result


def main():
    batches = load_batches()
    if not batches:
        raise SystemExit("no batch*/manifest.json found")

    out = []
    for b in batches:
        copy_assets(b)
        out.append(
            {
                "batch": b["batch"],
                "num": b["num"],
                "label": b["label"],
                "date": b["date"],
                "themes": to_theme_groups(b),
            }
        )

    # Foundations (the lowest-numbered batch) stays pinned at the top as the
    # reference set; every other batch follows newest-first. Python's sort is
    # stable, so the second pass only lifts the foundation without disturbing
    # the newest-first order of the rest.
    foundation_num = min(b["num"] for b in out)
    out.sort(key=lambda b: b["num"], reverse=True)
    out.sort(key=lambda b: b["num"] != foundation_num)

    ts = (
        "// AUTO-GENERATED by design/icon-options/build-registry.py.\n"
        "// Source of truth = design/icon-options/batch*/manifest.json.\n"
        "// To add a batch: run the `generate-app-icons` workflow, write its\n"
        "// design/icon-options/batch<N>/manifest.json (batch,num,label,date,themes,icons),\n"
        "// then rerun build-registry.py. Do not hand-edit this file.\n\n"
        "export type IconConcept = { id: string; file: string; name: string; concept: string; score: number | null };\n"
        "export type ThemeGroup = { title: string; icons: IconConcept[] };\n"
        "export type Batch = { batch: string; num: number; label: string; date: string; themes: ThemeGroup[] };\n\n"
        "export const BATCHES: Batch[] = " + json.dumps(out, indent=2) + ";\n"
    )
    with open(DATA_TS, "w") as f:
        f.write(ts)

    n_icons = sum(len(t["icons"]) for b in out for t in b["themes"])
    print(
        f"registry built: {len(out)} batches, {n_icons} icons -> {os.path.relpath(DATA_TS, ROOT)}"
    )
    for b in out:
        print(f"  {b['batch']} (B{b['num']}, {b['date']}, {b['label']}): "
              f"{sum(len(t['icons']) for t in b['themes'])} icons, {len(b['themes'])} themes")


if __name__ == "__main__":
    main()
